.\" @(#)$Id: appblob.1,v 2004.1 2004/10/14 22:35:31 jleffler Exp $
.\" @(#)Manual page: APPBLOB -- Blob Manipulation Example
.ds fC "Version: $Revision: 2004.1 $ ($Date: 2004/10/14 22:35:31 $)
.TH APPBLOB 1J "JLSS Informix Tools"
.SH NAME
appblob \(em Append a file to the value in a single blob field of a table
.SH SYNOPSIS
\fBappblob\fP [-Vnx] -d dbase [-u username -p password] -t table -c blobcolumn \e
.br
	-k column=value [-k col=val ...] [-f] blobfile
.SH DESCRIPTION
\fBAppblob\fP updates a table in the database so that a particular
file is appended to the blob (BYTE or TEXT) column of a pre-existing
row in the table which is identified by the combination of key column
and key value.
.P
You specify the database with the `\*c-d\*d' option, the table
with the `\*c-t\*d' option, and the column to be updated with the
`\*c-c\*d' option.
Optionally, you can specify the username and password with
the `\*c-u\*d' and `\*c-p\*d' options (not recommended for
security reasons, but possible nonetheless).
The file to be used can be specified with the `\*c-f\*d' option
or as the last argument on the line.
For each necessary key column, you use the `\*c-k\*d' option
followed by the column name and the value in that column for the
row to be updated.
The value will be converted into a string embedded in single
quotes, with any embedded single quotes doubled up so that the
SQL parser is happy.
This can get complicated because the shell also uses single and
double quotes too.
For example, to use a key column containing the string:
.P
.eS
    He said, "Don't delete me!"
.eE
.P
the command line might look like:
.P
.eS
appblob -d dbase -t blobs -c text_col -f new_blob_file \e
    -k char_col="He said, \e"Don't delete me!\e""
.eE
.P
The `\*c-x\*d' option prints the statements that are executed.
The `\*c-n\*d' option prevents the statement from being executed (it is,
however, prepared, so that it is checked for validity).
The `\*c-V\*d' option prints the version number of the program and exits.
.SH "ORIGINS"
On 2001-07-30, Adam Shartzer <ars4a@cms.mail.virginia.edu> wrote
asking about how to append a new file (in his case, a new email message)
to a previously existing blob.  The \fBupdblob\fP program does not
make this easy; you would have to use some program to unload the blob
to a file, then append the new material, and finally use \fBupdblob\fP to
replace the old value.  Of course, this loses all possibility of transaction
control, too.  On 2001-08-01, Jonathan Leffler provided a preliminary version
of \fBappblob\fP.  This preliminary version did not lock the rows properly.
Jonathan said, "This seems to work.  It is at least moderately robust - it cleans up
behind itself, with the possible (probable) exception of signal
handling.  Its structure isn't completely elegant -- the sequence of
nested if's and else's with about 5 levels of unwind at the end is ugly [...]
I have tested it on a null blob -- it appends OK.  [...]"
.SH "FUTURE DIRECTIONS"
It would be interesting to upgrade \fBappblob\fP to use a
command line notation such as this so that multiple blob columns in a
single row can be updated simultaneously:
.eS
    appblob -d dbase -t table -k key=value -c blobcol1=file1 \
        -c blobcol2=file2
.eE
You might even generalize it to replace some blobs and append or prepend
files to other blob columns:
.eS
    modblob -d dbase -t table -k key=value -r blobcol1=file1 \
        -a blobcol2=file2 -p blobcol3=file3
.eE
.eS
    -r replaces blobcol1 with file1;
    -a appends file2 to blobcol2;
    -p prepends file3 to blobcol3;
.eE
.SH "SEE ALSO"
updblob(1J), selblob(1J)
.SH DIAGNOSTICS
If no rows are updated, or if more than one row is updated, you get
a warning printed on stderr (but the command is still successful).
.P
If the SQL created is not valid, then you'll see the
SQL and ISAM error messages from the engine.
.SH BUGS
None known.
.SH AUTHOR
Jonathan Leffler
.br
JLSS
.br
8th September 2001
