#   @(#)$Id: Depend.mk,v 2013.1 2013/09/08 23:40:13 jleffler Exp $
#
#   @(#)@PACKAGE@ Version @VERSION@
#
#   Include file dependencies for SQLCMD/SQLUNLOAD/SQLRELOAD

# DO NOT DELETE THIS LINE or the blank line after it -- make depend uses them.

basedigit.o: basedigit.c
basedigit.o: config.h
basedigit.o: jlss.h
basename.o: basename.c
basename.o: config.h
basename.o: jlss.h
chkfifo.o: chkfifo.c
chkfifo.o: config.h
chkfifo.o: esql_ius.h
chkfifo.o: esqlc.h
chkfifo.o: esqltype.h
chkfifo.o: jlss.h
chkfifo.o: jlsstools.h
chkfifo.o: memory.h
chktty.o: chktty.c
chktty.o: chktty.h
chktty.o: config.h
chrcstrlit.o: chrcstrlit.c
chrcstrlit.o: config.h
chrcstrlit.o: jlss.h
cistrcmp.o: cistrcmp.c
cistrcmp.o: config.h
cistrcmp.o: jlss.h
connect.o: config.h
connect.o: connect.ec
connect.o: connect.h
connect.o: context.h
connect.o: emalloc.h
connect.o: esql_ius.h
connect.o: esqlc.h
connect.o: esqltype.h
connect.o: esqlutil.h
connect.o: internal.h
connect.o: jlss.h
connect.o: jlsstools.h
connect.o: memory.h
connect.o: sqlconn.h
connect.o: sqlerr.h
connecty.o: config.h
connecty.o: connect.h
connecty.o: context.h
connecty.o: emalloc.h
connecty.o: esql_ius.h
connecty.o: esqlc.h
connecty.o: esqltype.h
connecty.o: esqlutil.h
connecty.o: internal.h
connecty.o: jlss.h
connecty.o: sqlconn.h
connecty.o: sqltoken.h
connecty.o: stderr.h
connecty.o: strdotfill.h
conninfo.o: config.h
conninfo.o: connect.h
conninfo.o: conninfo.c
conninfo.o: context.h
conninfo.o: debug.h
conninfo.o: emalloc.h
conninfo.o: esql_ius.h
conninfo.o: esqlc.h
conninfo.o: esqltype.h
conninfo.o: esqlutil.h
conninfo.o: internal.h
conninfo.o: jlss.h
conninfo.o: jlsstools.h
conninfo.o: memory.h
conninfo.o: sqlconn.h
conninfo.o: sqlerr.h
context.o: config.h
context.o: context.c
context.o: context.h
context.o: datefmt.h
context.o: emalloc.h
context.o: esql_ius.h
context.o: esqlc.h
context.o: esqltype.h
context.o: history.h
context.o: jlss.h
context.o: jlsstools.h
context.o: memory.h
context.o: readcmd.h
context.o: sqlcmd.h
context.o: sqlerr.h
context.o: stderr.h
context.o: stldint.h
cstrlitchr.o: config.h
cstrlitchr.o: cstrlitchr.c
cstrlitchr.o: jlss.h
cstrlitstr.o: config.h
cstrlitstr.o: cstrlitstr.c
cstrlitstr.o: jlss.h
datefmt.o: datefmt.c
datefmt.o: datefmt.h
debug.o: config.h
debug.o: debug.c
debug.o: debug.h
debug.o: stderr.h
decfix.o: decfix.c
decfix.o: decsci.h
decfix.o: esqltype.h
decfix.o: ifmxdec.h
decsci.o: decsci.c
decsci.o: decsci.h
decsci.o: esqltype.h
decsci.o: ifmxdec.h
decsetexp.o: decsci.h
decsetexp.o: decsetexp.c
decsetexp.o: esqltype.h
decsetexp.o: ifmxdec.h
describe.o: config.h
describe.o: debug.h
describe.o: describe.ec
describe.o: describe.h
describe.o: emalloc.h
describe.o: esql_ius.h
describe.o: esqlc.h
describe.o: esqltype.h
describe.o: esqlutil.h
describe.o: ixblob.h
dumpblob.o: config.h
dumpblob.o: dumpblob.ec
dumpblob.o: dumpconfig.h
dumpblob.o: dumpesql.h
dumpblob.o: esql_ius.h
dumpblob.o: esqlc.h
dumpblob.o: esqltype.h
dumpblob.o: esqlutil.h
dumpdec.o: config.h
dumpdec.o: dumpconfig.h
dumpdec.o: dumpdec.ec
dumpdec.o: dumpesql.h
dumpdec.o: esql_ius.h
dumpdec.o: esqlc.h
dumpdec.o: esqltype.h
dumpdtime.o: config.h
dumpdtime.o: decsci.h
dumpdtime.o: dumpconfig.h
dumpdtime.o: dumpdtime.ec
dumpdtime.o: dumpesql.h
dumpdtime.o: esql_ius.h
dumpdtime.o: esqlc.h
dumpdtime.o: esqltype.h
dumpdtime.o: esqlutil.h
dumpdtime.o: ifmxdec.h
dumpindent.o: config.h
dumpindent.o: dumpesql.h
dumpindent.o: dumpindent.c
dumpindent.o: esql_ius.h
dumpindent.o: esqlc.h
dumpindent.o: esqltype.h
dumpintvl.o: config.h
dumpintvl.o: decsci.h
dumpintvl.o: dumpconfig.h
dumpintvl.o: dumpesql.h
dumpintvl.o: dumpintvl.ec
dumpintvl.o: esql_ius.h
dumpintvl.o: esqlc.h
dumpintvl.o: esqltype.h
dumpintvl.o: esqlutil.h
dumpintvl.o: ifmxdec.h
dumpsqlca.o: config.h
dumpsqlca.o: dumpesql.h
dumpsqlca.o: dumpsqlca.ec
dumpsqlca.o: esql_ius.h
dumpsqlca.o: esqlc.h
dumpsqlca.o: esqltype.h
dumpsqlca.o: esqlutil.h
dumpsqlda.o: config.h
dumpsqlda.o: dumpconfig.h
dumpsqlda.o: dumpesql.h
dumpsqlda.o: dumpsqlda.ec
dumpsqlda.o: esql_ius.h
dumpsqlda.o: esqlc.h
dumpsqlda.o: esqltype.h
dumpsqlda.o: esqlutil.h
dumpvalue.o: config.h
dumpvalue.o: dumpconfig.h
dumpvalue.o: dumpesql.h
dumpvalue.o: dumpvalue.ec
dumpvalue.o: esql_ius.h
dumpvalue.o: esqlc.h
dumpvalue.o: esqltype.h
dumpvalue.o: esqlutil.h
efopen.o: config.h
efopen.o: efopen.c
efopen.o: esql_ius.h
efopen.o: esqlc.h
efopen.o: esqltype.h
efopen.o: jlss.h
efopen.o: jlsstools.h
efopen.o: memory.h
efopen.o: sqlerr.h
emalloc.o: config.h
emalloc.o: debug.h
emalloc.o: emalloc.c
emalloc.o: emalloc.h
emalloc.o: stderr.h
epopen.o: config.h
epopen.o: epopen.c
epopen.o: esql_ius.h
epopen.o: esqlc.h
epopen.o: esqltype.h
epopen.o: jlss.h
epopen.o: jlsstools.h
epopen.o: memory.h
epopen.o: sqlerr.h
errhelp.o: config.h
errhelp.o: errhelp.c
errhelp.o: stderr.h
esnprintf.o: config.h
esnprintf.o: esnprintf.c
esnprintf.o: esnprintf.h
esnprintf.o: posixver.h
esnprintf.o: stderr.h
esqlcver.o: config.h
esqlcver.o: esql_ius.h
esqlcver.o: esqlc.h
esqlcver.o: esqlcver.ec
esqlcver.o: esqltype.h
esqlcver.o: esqlutil.h
esqlver.o: config.h
esqlver.o: esql_ius.h
esqlver.o: esqlc.h
esqlver.o: esqltype.h
esqlver.o: esqlver.c
esqlver.o: jlss.h
esqlver.o: jlsstools.h
esqlver.o: memory.h
estrdup.o: config.h
estrdup.o: emalloc.h
estrdup.o: estrdup.c
fcopy.o: config.h
fcopy.o: fcopy.c
fcopy.o: jlss.h
fcopy.o: stderr.h
filelock.o: config.h
filelock.o: filelock.c
filelock.o: filelock.h
filelock.o: stderr.h
fmkstemp.o: config.h
fmkstemp.o: fmkstemp.c
fmkstemp.o: jlss.h
getline.o: config.h
getline.o: getline.c
getline.o: jlss.h
getline.o: kludge.h
getopt.o: config.h
getopt.o: getopt.c
getopt.o: getopt.h
getsubopt.o: config.h
getsubopt.o: getopt.h
getsubopt.o: getsubopt.c
guesser.o: config.h
guesser.o: esql_ius.h
guesser.o: esqlc.h
guesser.o: esqltype.h
guesser.o: guesser.c
guesser.o: sqlconn.h
guesser.o: stderr.h
guesser.o: upload.h
histdump.o: config.h
histdump.o: getopt.h
histdump.o: histdump.c
histdump.o: history.h
histdump.o: jlss.h
histdump.o: stderr.h
histdump.o: stldint.h
history.o: config.h
history.o: emalloc.h
history.o: esql_ius.h
history.o: esqlc.h
history.o: esqltype.h
history.o: filelock.h
history.o: history.c
history.o: history.h
history.o: jlss.h
history.o: jlsstools.h
history.o: memory.h
history.o: sqlcmd.h
history.o: stderr.h
history.o: stldint.h
ifmxdec.o: decsci.h
ifmxdec.o: esqltype.h
ifmxdec.o: ifmxdec.c
ifmxdec.o: ifmxdec.h
ilog10.o: ilog10.c
ilog10.o: ilog10.h
internal.o: config.h
internal.o: connect.h
internal.o: context.h
internal.o: emalloc.h
internal.o: esnprintf.h
internal.o: esql_ius.h
internal.o: esqlc.h
internal.o: esqltype.h
internal.o: esqlutil.h
internal.o: history.h
internal.o: internal.c
internal.o: internal.h
internal.o: ixblob.h
internal.o: jlss.h
internal.o: jlsstools.h
internal.o: kludge.h
internal.o: memory.h
internal.o: openfile.h
internal.o: readcmd.h
internal.o: sqlcmd.h
internal.o: sqlconn.h
internal.o: sqlerr.h
internal.o: sqltoken.h
internal.o: stderr.h
internal.o: stldint.h
internal.o: sysstat.h
internal.o: timer.h
iustoken.o: config.h
iustoken.o: debug.h
iustoken.o: iustoken.c
iustoken.o: sqltoken.h
iustoken.o: tokencmp.h
ixblob.o: config.h
ixblob.o: esql_ius.h
ixblob.o: esqlc.h
ixblob.o: esqltype.h
ixblob.o: ixblob.ec
ixblob.o: ixblob.h
jtypes.o: config.h
jtypes.o: esql_ius.h
jtypes.o: esqlc.h
jtypes.o: esqltype.h
jtypes.o: esqlutil.h
jtypes.o: jtypes.c
jtypes.o: stderr.h
kludge.o: kludge.c
kludge.o: kludge.h
lduint4.o: config.h
lduint4.o: lduint4.c
lduint4.o: stldint.h
memory.o: config.h
memory.o: emalloc.h
memory.o: memory.c
memory.o: memory.h
memory.o: sqlerr.h
mkpath.o: config.h
mkpath.o: emalloc.h
mkpath.o: jlss.h
mkpath.o: mkpath.c
mkpath.o: sysstat.h
mkproc.o: config.h
mkproc.o: esqltype.h
mkproc.o: getopt.h
mkproc.o: mkproc.ec
mkproc.o: stderr.h
nstrcpy.o: config.h
nstrcpy.o: jlss.h
nstrcpy.o: nstrcpy.c
nvstrcpy.o: config.h
nvstrcpy.o: jlss.h
nvstrcpy.o: nvstrcpy.c
output.o: config.h
output.o: context.h
output.o: decsci.h
output.o: describe.h
output.o: emalloc.h
output.o: esnprintf.h
output.o: esql_ius.h
output.o: esqlc.h
output.o: esqltype.h
output.o: esqlutil.h
output.o: ifmxdec.h
output.o: internal.h
output.o: ixblob.h
output.o: jlss.h
output.o: jlsstools.h
output.o: kludge.h
output.o: memory.h
output.o: output.c
output.o: output.h
output.o: sqlcmd.h
output.o: sqlerr.h
output.o: usesqlda.h
quotify.o: config.h
quotify.o: esnprintf.h
quotify.o: esql_ius.h
quotify.o: esqlc.h
quotify.o: esqltype.h
quotify.o: jlss.h
quotify.o: jlsstools.h
quotify.o: memory.h
quotify.o: quotify.c
readcmd.o: chktty.h
readcmd.o: config.h
readcmd.o: esnprintf.h
readcmd.o: gnureadline.h
readcmd.o: kludge.h
readcmd.o: readcmd.c
readcmd.o: readcmd.h
readcmd.o: sqltoken.h
readcmd.o: tokencmp.h
readload.o: config.h
readload.o: context.h
readload.o: debug.h
readload.o: dumpesql.h
readload.o: esql_ius.h
readload.o: esqlc.h
readload.o: esqltype.h
readload.o: esqlutil.h
readload.o: jlss.h
readload.o: jlsstools.h
readload.o: kludge.h
readload.o: memory.h
readload.o: readload.c
readload.o: sqlcmd.h
readload.o: sqlerr.h
readload.o: stderr.h
reload.o: config.h
reload.o: context.h
reload.o: debug.h
reload.o: describe.h
reload.o: dumpesql.h
reload.o: emalloc.h
reload.o: esnprintf.h
reload.o: esql_ius.h
reload.o: esqlc.h
reload.o: esqltype.h
reload.o: esqlutil.h
reload.o: internal.h
reload.o: jlss.h
reload.o: jlsstools.h
reload.o: kludge.h
reload.o: memory.h
reload.o: reload.ec
reload.o: sqlcmd.h
reload.o: sqlerr.h
reload.o: sqltoken.h
reload.o: stderr.h
reload.o: tokencmp.h
scribble.o: config.h
scribble.o: esql_ius.h
scribble.o: esqlc.h
scribble.o: esqltype.h
scribble.o: jlss.h
scribble.o: jlsstools.h
scribble.o: memory.h
scribble.o: scribble.c
skip.o: internal.h
skip.o: skip.c
sqlcmd.o: chktty.h
sqlcmd.o: config.h
sqlcmd.o: connect.h
sqlcmd.o: context.h
sqlcmd.o: debug.h
sqlcmd.o: describe.h
sqlcmd.o: emalloc.h
sqlcmd.o: esql_ius.h
sqlcmd.o: esqlc.h
sqlcmd.o: esqltype.h
sqlcmd.o: getopt.h
sqlcmd.o: history.h
sqlcmd.o: internal.h
sqlcmd.o: jlss.h
sqlcmd.o: jlsstools.h
sqlcmd.o: memory.h
sqlcmd.o: output.h
sqlcmd.o: sqlcmd.c
sqlcmd.o: sqlcmd.h
sqlcmd.o: sqlconn.h
sqlcmd.o: sqlerr.h
sqlcmd.o: stderr.h
sqlcmd.o: stldint.h
sqlconn.o: config.h
sqlconn.o: debug.h
sqlconn.o: esnprintf.h
sqlconn.o: esql_ius.h
sqlconn.o: esqlc.h
sqlconn.o: esqltype.h
sqlconn.o: jlss.h
sqlconn.o: sqlconn.ec
sqlconn.o: sqlconn.h
sqlconn.o: stderr.h
sqlconn.o: strdotfill.h
sqlconn.o: tokencmp.h
sqlerr.o: config.h
sqlerr.o: context.h
sqlerr.o: emalloc.h
sqlerr.o: esnprintf.h
sqlerr.o: esql_ius.h
sqlerr.o: esqlc.h
sqlerr.o: esqltype.h
sqlerr.o: esqlutil.h
sqlerr.o: jlss.h
sqlerr.o: jlsstools.h
sqlerr.o: memory.h
sqlerr.o: sqlcmd.h
sqlerr.o: sqlerr.c
sqlerr.o: sqlerr.h
sqlerr.o: stderr.h
sqlinfo.o: config.h
sqlinfo.o: connect.h
sqlinfo.o: context.h
sqlinfo.o: debug.h
sqlinfo.o: emalloc.h
sqlinfo.o: esnprintf.h
sqlinfo.o: esql_ius.h
sqlinfo.o: esqlc.h
sqlinfo.o: esqltype.h
sqlinfo.o: esqlutil.h
sqlinfo.o: internal.h
sqlinfo.o: jlss.h
sqlinfo.o: jlsstools.h
sqlinfo.o: memory.h
sqlinfo.o: sqlconn.h
sqlinfo.o: sqlerr.h
sqlinfo.o: sqlinfo.ec
sqlinfo.o: sqlownobj.h
sqlownobj.o: config.h
sqlownobj.o: debug.h
sqlownobj.o: esql_ius.h
sqlownobj.o: esqlc.h
sqlownobj.o: esqltype.h
sqlownobj.o: esqlutil.h
sqlownobj.o: jlss.h
sqlownobj.o: sqlownobj.ec
sqlownobj.o: sqlownobj.h
sqlownobj.o: sqlquote.h
sqlprint.o: config.h
sqlprint.o: esql_ius.h
sqlprint.o: esqlc.h
sqlprint.o: esqltype.h
sqlprint.o: esqlutil.h
sqlprint.o: sqlprint.c
sqlquote.o: sqlquote.c
sqlquote.o: sqlquote.h
sqlsignal.o: config.h
sqlsignal.o: esql_ius.h
sqlsignal.o: esqlc.h
sqlsignal.o: esqltype.h
sqlsignal.o: jlss.h
sqlsignal.o: jlsstools.h
sqlsignal.o: memory.h
sqlsignal.o: sqlcmd.h
sqlsignal.o: sqlerr.h
sqlsignal.o: sqlsignal.c
sqlstmt.o: config.h
sqlstmt.o: connect.h
sqlstmt.o: context.h
sqlstmt.o: debug.h
sqlstmt.o: describe.h
sqlstmt.o: emalloc.h
sqlstmt.o: esnprintf.h
sqlstmt.o: esql_ius.h
sqlstmt.o: esqlc.h
sqlstmt.o: esqltype.h
sqlstmt.o: internal.h
sqlstmt.o: jlss.h
sqlstmt.o: jlsstools.h
sqlstmt.o: memory.h
sqlstmt.o: output.h
sqlstmt.o: sqlcmd.h
sqlstmt.o: sqlconn.h
sqlstmt.o: sqlerr.h
sqlstmt.o: sqlstmt.ec
sqltoken.o: config.h
sqltoken.o: debug.h
sqltoken.o: sqltoken.c
sqltoken.o: sqltoken.h
sqltype.o: config.h
sqltype.o: esql_ius.h
sqltype.o: esqlc.h
sqltype.o: esqltype.h
sqltype.o: esqlutil.h
sqltype.o: sqltype.ec
sqlunquote.o: sqlquote.h
sqlunquote.o: sqlunquote.c
sqlupload.o: config.h
sqlupload.o: context.h
sqlupload.o: debug.h
sqlupload.o: emalloc.h
sqlupload.o: esql_ius.h
sqlupload.o: esqlc.h
sqlupload.o: esqltype.h
sqlupload.o: getopt.h
sqlupload.o: jlss.h
sqlupload.o: jlsstools.h
sqlupload.o: memory.h
sqlupload.o: sqlcmd.h
sqlupload.o: sqlconn.h
sqlupload.o: sqlerr.h
sqlupload.o: sqlupload.c
sqlupload.o: stderr.h
sqlupload.o: upload.h
sqlver.o: config.h
sqlver.o: esnprintf.h
sqlver.o: esql_ius.h
sqlver.o: esqlc.h
sqlver.o: esqltype.h
sqlver.o: gnureadline.h
sqlver.o: internal.h
sqlver.o: jlss.h
sqlver.o: jlsstools.h
sqlver.o: memory.h
sqlver.o: sqlver.c
sqlver.o: stderr.h
stderr.o: config.h
stderr.o: stderr.c
stderr.o: stderr.h
strcstrlit.o: config.h
strcstrlit.o: jlss.h
strcstrlit.o: strcstrlit.c
strlower.o: config.h
strlower.o: jlss.h
strlower.o: strlower.c
strprefix.o: config.h
strprefix.o: jlss.h
strprefix.o: strprefix.c
strupper.o: config.h
strupper.o: jlss.h
strupper.o: strupper.c
stuint4.o: config.h
stuint4.o: stldint.h
stuint4.o: stuint4.c
timer.o: config.h
timer.o: timer.c
timer.o: timer.h
tokencmp.o: tokencmp.c
tokencmp.o: tokencmp.h
updblob.o: config.h
updblob.o: connblob.h
updblob.o: debug.h
updblob.o: esnprintf.h
updblob.o: esql_ius.h
updblob.o: esqlc.h
updblob.o: esqltype.h
updblob.o: getopt.h
updblob.o: stderr.h
updblob.o: updblob.ec
upload.o: config.h
upload.o: connect.h
upload.o: context.h
upload.o: debug.h
upload.o: describe.h
upload.o: dumpesql.h
upload.o: emalloc.h
upload.o: esnprintf.h
upload.o: esql_ius.h
upload.o: esqlc.h
upload.o: esqltype.h
upload.o: esqlutil.h
upload.o: jlss.h
upload.o: jlsstools.h
upload.o: kludge.h
upload.o: memory.h
upload.o: sqlcmd.h
upload.o: sqlconn.h
upload.o: sqlerr.h
upload.o: sqlownobj.h
upload.o: stderr.h
upload.o: upload.ec
upload.o: upload.h
upload.o: usesqlda.h
usesqlda.o: config.h
usesqlda.o: esql_ius.h
usesqlda.o: esqlc.h
usesqlda.o: esqltype.h
usesqlda.o: usesqlda.c
usesqlda.o: usesqlda.h
vstrcpy.o: config.h
vstrcpy.o: jlss.h
vstrcpy.o: vstrcpy.c
