'\" @(#)$Id: sqlserver.1,v 1.1 1998/10/20 06:19:06 jleffler Exp $
'\" @(#)Manual page: SQLSERVER/SQLCLIENT -- background database access
'\" @(#)SQLCMD Version 90.02 (2016-07-28)
.ds fC "Version: $Revision: 1.1 $ ($Date: 1998/10/20 06:19:06 $)
.TH SQLSERVER 1S "JLSS Informix Tools"
.SH NAME
sqlserver \(em run SQLCMD as a server process
.br
newserver \(em run SQLCMD as a server process on a new FIFO
.br
sqlclient \(em process SQL commands via sqlserver
.br
sql \(em synonym for sqlclient
.SH SYNOPSIS
\fBsqlserver\fP [-d database]
.br
\fB. newserver\fP [-d database]
.br
\fBsqlclient\fP "sql command" [...]
.br
\fBsql\fP "sql command" [...]
.SH DESCRIPTION
Details TBS
.P
.SH DETAILS
.SH SEE ALSO
Informix Reference Manuals and Tech Notes.
sed(1).
.SH BUGS
Probably.
.SH VERSION
The current version of this product is SQLCMD Version 90.02 (2016-07-28).
.SH AUTHOR
Jonathan Leffler
.br
JLSS
.br
19th October 1998
