#	@(#)$Id: Depend.mk,v 1.17 2006/01/06 18:34:27 jleffler Exp $
#
#   @(#)@PACKAGE@ Version @VERSION@
#
#	Include file dependencies for SQLCMD/SQLUNLOAD/SQLRELOAD on Windows (NT/2K/XP)

# DO NOT DELETE THIS LINE or the blank line after it -- make depend uses them.

basedigit.obj: basedigit.c
basedigit.obj: jlss.h
basename.obj: basename.c
basename.obj: jlss.h
chkfifo.obj: chkfifo.c
chkfifo.obj: chktty.h
chkfifo.obj: config.h
chkfifo.obj: esqlc.h
chkfifo.obj: esqltype.h
chkfifo.obj: jlss.h
chkfifo.obj: jlsstools.h
chkfifo.obj: memory.h
chktty.obj: chktty.c
chktty.obj: chktty.h
chktty.obj: config.h
chrcstrlit.obj: chrcstrlit.c
chrcstrlit.obj: jlss.h
cistrcmp.obj: cistrcmp.c
cistrcmp.obj: jlss.h
connect.obj: chktty.h
connect.obj: config.h
connect.obj: connect.ec
connect.obj: connect.h
connect.obj: context.h
connect.obj: esqlc.h
connect.obj: esqltype.h
connect.obj: esqlutil.h
connect.obj: internal.h
connect.obj: jlss.h
connect.obj: jlsstools.h
connect.obj: memory.h
connect.obj: sqlconn.h
connect.obj: sqlerr.h
connect.obj: sqlquote.h
connecty.obj: config.h
connecty.obj: connect.h
connecty.obj: connecty.y
connecty.obj: context.h
connecty.obj: esqlc.h
connecty.obj: esqltype.h
connecty.obj: esqlutil.h
connecty.obj: internal.h
connecty.obj: jlss.h
connecty.obj: sqlconn.h
connecty.obj: sqlquote.h
connecty.obj: sqltoken.h
connecty.obj: stderr.h
connecty.obj: strdotfill.h
conninfo.obj: chktty.h
conninfo.obj: config.h
conninfo.obj: connect.h
conninfo.obj: conninfo.c
conninfo.obj: context.h
conninfo.obj: debug.h
conninfo.obj: emalloc.h
conninfo.obj: esqlc.h
conninfo.obj: esqltype.h
conninfo.obj: esqlutil.h
conninfo.obj: internal.h
conninfo.obj: jlss.h
conninfo.obj: jlsstools.h
conninfo.obj: memory.h
conninfo.obj: sqlconn.h
conninfo.obj: sqlerr.h
conninfo.obj: sqlquote.h
context.obj: chktty.h
context.obj: config.h
context.obj: context.c
context.obj: context.h
context.obj: datefmt.h
context.obj: emalloc.h
context.obj: esqlc.h
context.obj: esqltype.h
context.obj: history.h
context.obj: jlss.h
context.obj: jlsstools.h
context.obj: memory.h
context.obj: readcmd.h
context.obj: sqlcmd.h
context.obj: sqlerr.h
context.obj: stderr.h
context.obj: stldint.h
cstrlitchr.obj: cstrlitchr.c
cstrlitchr.obj: jlss.h
cstrlitstr.obj: cstrlitstr.c
cstrlitstr.obj: jlss.h
datefmt.obj: datefmt.c
datefmt.obj: datefmt.h
debug.obj: debug.c
debug.obj: debug.h
debug.obj: stderr.h
decfix.obj: config.h
decfix.obj: decfix.c
decfix.obj: decsci.h
decfix.obj: esqlc.h
decfix.obj: esqltype.h
decfix.obj: ifmxdec.h
decsci.obj: config.h
decsci.obj: decintl.h
decsci.obj: decsci.c
decsci.obj: decsci.h
decsci.obj: esqlc.h
decsci.obj: esqltype.h
decsci.obj: ifmxdec.h
decsetexp.obj: decintl.h
decsetexp.obj: decsetexp.c
describe.obj: config.h
describe.obj: describe.ec
describe.obj: describe.h
describe.obj: emalloc.h
describe.obj: esqlc.h
describe.obj: esqltype.h
describe.obj: esqlutil.h
describe.obj: ixblob.h
describe.obj: sqlquote.h
dumpblob.obj: config.h
dumpblob.obj: dumpblob.ec
dumpblob.obj: esqlc.h
dumpblob.obj: esqltype.h
dumpblob.obj: esqlutil.h
dumpblob.obj: sqlquote.h
dumpdec.obj: config.h
dumpdec.obj: dumpdec.ec
dumpdec.obj: esqlc.h
dumpdec.obj: esqltype.h
dumpdec.obj: esqlutil.h
dumpdec.obj: sqlquote.h
dumpdtime.obj: config.h
dumpdtime.obj: dumpdtime.ec
dumpdtime.obj: esqlc.h
dumpdtime.obj: esqltype.h
dumpdtime.obj: esqlutil.h
dumpdtime.obj: sqlquote.h
dumpintvl.obj: config.h
dumpintvl.obj: dumpintvl.ec
dumpintvl.obj: esqlc.h
dumpintvl.obj: esqltype.h
dumpintvl.obj: esqlutil.h
dumpintvl.obj: sqlquote.h
dumpsqlca.obj: config.h
dumpsqlca.obj: dumpsqlca.ec
dumpsqlca.obj: esqlc.h
dumpsqlca.obj: esqltype.h
dumpsqlca.obj: esqlutil.h
dumpsqlca.obj: sqlquote.h
dumpsqlda.obj: config.h
dumpsqlda.obj: dumpsqlda.ec
dumpsqlda.obj: esqlc.h
dumpsqlda.obj: esqltype.h
dumpsqlda.obj: esqlutil.h
dumpsqlda.obj: sqlquote.h
dumpvalue.obj: config.h
dumpvalue.obj: dumpvalue.ec
dumpvalue.obj: esqlc.h
dumpvalue.obj: esqltype.h
dumpvalue.obj: esqlutil.h
dumpvalue.obj: sqlquote.h
efopen.obj: chktty.h
efopen.obj: config.h
efopen.obj: efopen.c
efopen.obj: esqlc.h
efopen.obj: esqltype.h
efopen.obj: jlss.h
efopen.obj: jlsstools.h
efopen.obj: memory.h
efopen.obj: sqlerr.h
emalloc.obj: debug.h
emalloc.obj: emalloc.c
emalloc.obj: emalloc.h
emalloc.obj: stderr.h
epopen.obj: chktty.h
epopen.obj: config.h
epopen.obj: epopen.c
epopen.obj: esqlc.h
epopen.obj: esqltype.h
epopen.obj: jlss.h
epopen.obj: jlsstools.h
epopen.obj: memory.h
epopen.obj: sqlerr.h
esqlcver.obj: config.h
esqlcver.obj: esqlc.h
esqlcver.obj: esqlcver.ec
esqlcver.obj: esqltype.h
esqlcver.obj: esqlutil.h
esqlcver.obj: sqlquote.h
esqlver.obj: chktty.h
esqlver.obj: config.h
esqlver.obj: esqlc.h
esqlver.obj: esqltype.h
esqlver.obj: esqlver.c
esqlver.obj: jlss.h
esqlver.obj: jlsstools.h
esqlver.obj: memory.h
estrdup.obj: config.h
estrdup.obj: emalloc.h
estrdup.obj: estrdup.c
fcopy.obj: fcopy.c
fcopy.obj: jlss.h
fcopy.obj: stderr.h
filelock.obj: config.h
filelock.obj: filelock.c
filelock.obj: filelock.h
getline.obj: getline.c
getline.obj: jlss.h
getline.obj: kludge.h
getopt.obj: getopt.c
getopt.obj: getopt.h
getsubopt.obj: getopt.h
getsubopt.obj: getsubopt.c
guesser.obj: config.h
guesser.obj: guesser.c
guesser.obj: upload.h
histdump.obj: config.h
histdump.obj: getopt.h
histdump.obj: histdump.c
histdump.obj: history.h
histdump.obj: jlss.h
histdump.obj: stderr.h
histdump.obj: stldint.h
history.obj: chktty.h
history.obj: config.h
history.obj: emalloc.h
history.obj: esqlc.h
history.obj: esqltype.h
history.obj: filelock.h
history.obj: history.c
history.obj: history.h
history.obj: jlss.h
history.obj: jlsstools.h
history.obj: memory.h
history.obj: sqlcmd.h
history.obj: stderr.h
history.obj: stldint.h
internal.obj: chktty.h
internal.obj: config.h
internal.obj: connect.h
internal.obj: context.h
internal.obj: esqlc.h
internal.obj: esqltype.h
internal.obj: esqlutil.h
internal.obj: history.h
internal.obj: internal.c
internal.obj: internal.h
internal.obj: jlss.h
internal.obj: jlsstools.h
internal.obj: kludge.h
internal.obj: memory.h
internal.obj: openfile.h
internal.obj: readcmd.h
internal.obj: sqlcmd.h
internal.obj: sqlconn.h
internal.obj: sqlerr.h
internal.obj: sqlquote.h
internal.obj: sqltoken.h
internal.obj: stderr.h
internal.obj: stldint.h
internal.obj: timer.h
iustoken.obj: config.h
iustoken.obj: debug.h
iustoken.obj: iustoken.c
iustoken.obj: jlss.h
iustoken.obj: sqltoken.h
ixblob.obj: config.h
ixblob.obj: esqlc.h
ixblob.obj: esqltype.h
ixblob.obj: ixblob.ec
ixblob.obj: ixblob.h
jtypes.obj: config.h
jtypes.obj: esqlc.h
jtypes.obj: esqltype.h
jtypes.obj: esqlutil.h
jtypes.obj: jtypes.c
jtypes.obj: sqlquote.h
jtypes.obj: stderr.h
kludge.obj: kludge.c
kludge.obj: kludge.h
lduint4.obj: config.h
lduint4.obj: lduint4.c
lduint4.obj: stldint.h
memory.obj: config.h
memory.obj: emalloc.h
memory.obj: memory.c
memory.obj: memory.h
memory.obj: sqlerr.h
mkpath.obj: emalloc.h
mkpath.obj: jlss.h
mkpath.obj: mkpath.c
mkproc.obj: config.h
mkproc.obj: getopt.h
mkproc.obj: mkproc.ec
mkproc.obj: stderr.h
nstrcpy.obj: jlss.h
nstrcpy.obj: nstrcpy.c
nvstrcpy.obj: jlss.h
nvstrcpy.obj: nvstrcpy.c
output.obj: chktty.h
output.obj: config.h
output.obj: context.h
output.obj: decsci.h
output.obj: describe.h
output.obj: emalloc.h
output.obj: esqlc.h
output.obj: esqltype.h
output.obj: esqlutil.h
output.obj: ifmxdec.h
output.obj: internal.h
output.obj: ixblob.h
output.obj: jlss.h
output.obj: jlsstools.h
output.obj: kludge.h
output.obj: memory.h
output.obj: output.c
output.obj: output.h
output.obj: sqlcmd.h
output.obj: sqlerr.h
output.obj: sqlquote.h
quotify.obj: chktty.h
quotify.obj: config.h
quotify.obj: esqlc.h
quotify.obj: esqltype.h
quotify.obj: jlss.h
quotify.obj: jlsstools.h
quotify.obj: memory.h
quotify.obj: quotify.c
readcmd.obj: chktty.h
readcmd.obj: config.h
readcmd.obj: readcmd.c
readcmd.obj: readcmd.h
readcmd.obj: sqltoken.h
readcmd.obj: tokencmp.h
readload.obj: chktty.h
readload.obj: config.h
readload.obj: context.h
readload.obj: debug.h
readload.obj: esqlc.h
readload.obj: esqltype.h
readload.obj: esqlutil.h
readload.obj: jlss.h
readload.obj: jlsstools.h
readload.obj: kludge.h
readload.obj: memory.h
readload.obj: readload.c
readload.obj: sqlcmd.h
readload.obj: sqlerr.h
readload.obj: sqlquote.h
readload.obj: stderr.h
reload.obj: chktty.h
reload.obj: config.h
reload.obj: context.h
reload.obj: debug.h
reload.obj: describe.h
reload.obj: emalloc.h
reload.obj: esqlc.h
reload.obj: esqltype.h
reload.obj: esqlutil.h
reload.obj: internal.h
reload.obj: jlss.h
reload.obj: jlsstools.h
reload.obj: kludge.h
reload.obj: memory.h
reload.obj: reload.ec
reload.obj: sqlcmd.h
reload.obj: sqlerr.h
reload.obj: sqlquote.h
reload.obj: sqltoken.h
reload.obj: stderr.h
reload.obj: tokencmp.h
skip.obj: internal.h
skip.obj: skip.c
sqlcmd.obj: chktty.h
sqlcmd.obj: config.h
sqlcmd.obj: connect.h
sqlcmd.obj: context.h
sqlcmd.obj: debug.h
sqlcmd.obj: describe.h
sqlcmd.obj: emalloc.h
sqlcmd.obj: esqlc.h
sqlcmd.obj: esqltype.h
sqlcmd.obj: getopt.h
sqlcmd.obj: history.h
sqlcmd.obj: internal.h
sqlcmd.obj: jlss.h
sqlcmd.obj: jlsstools.h
sqlcmd.obj: memory.h
sqlcmd.obj: output.h
sqlcmd.obj: sqlcmd.c
sqlcmd.obj: sqlcmd.h
sqlcmd.obj: sqlconn.h
sqlcmd.obj: sqlerr.h
sqlcmd.obj: stderr.h
sqlcmd.obj: stldint.h
sqlconn.obj: config.h
sqlconn.obj: debug.h
sqlconn.obj: esqlc.h
sqlconn.obj: esqltype.h
sqlconn.obj: jlss.h
sqlconn.obj: sqlconn.ec
sqlconn.obj: sqlconn.h
sqlconn.obj: sqlerr.h
sqlconn.obj: stderr.h
sqlconn.obj: strdotfill.h
sqlconn.obj: tokencmp.h
sqlerr.obj: chktty.h
sqlerr.obj: config.h
sqlerr.obj: context.h
sqlerr.obj: emalloc.h
sqlerr.obj: esqlc.h
sqlerr.obj: esqltype.h
sqlerr.obj: esqlutil.h
sqlerr.obj: jlss.h
sqlerr.obj: jlsstools.h
sqlerr.obj: memory.h
sqlerr.obj: sqlcmd.h
sqlerr.obj: sqlerr.c
sqlerr.obj: sqlerr.h
sqlerr.obj: sqlquote.h
sqlerr.obj: stderr.h
sqlinfo.obj: chktty.h
sqlinfo.obj: config.h
sqlinfo.obj: connect.h
sqlinfo.obj: context.h
sqlinfo.obj: debug.h
sqlinfo.obj: emalloc.h
sqlinfo.obj: esqlc.h
sqlinfo.obj: esqltype.h
sqlinfo.obj: esqlutil.h
sqlinfo.obj: internal.h
sqlinfo.obj: jlss.h
sqlinfo.obj: jlsstools.h
sqlinfo.obj: memory.h
sqlinfo.obj: sqlconn.h
sqlinfo.obj: sqlerr.h
sqlinfo.obj: sqlinfo.ec
sqlinfo.obj: sqlquote.h
sqlownobj.obj: config.h
sqlownobj.obj: debug.h
sqlownobj.obj: esqlc.h
sqlownobj.obj: esqltype.h
sqlownobj.obj: esqlutil.h
sqlownobj.obj: jlss.h
sqlownobj.obj: sqlownobj.ec
sqlownobj.obj: sqlquote.h
sqlprint.obj: config.h
sqlprint.obj: esqlc.h
sqlprint.obj: esqltype.h
sqlprint.obj: esqlutil.h
sqlprint.obj: sqlprint.c
sqlprint.obj: sqlquote.h
sqlquote.obj: sqlquote.c
sqlquote.obj: sqlquote.h
sqlsignal.obj: chktty.h
sqlsignal.obj: config.h
sqlsignal.obj: esqlc.h
sqlsignal.obj: esqltype.h
sqlsignal.obj: jlss.h
sqlsignal.obj: jlsstools.h
sqlsignal.obj: memory.h
sqlsignal.obj: sqlcmd.h
sqlsignal.obj: sqlerr.h
sqlsignal.obj: sqlsignal.c
sqlstmt.obj: chktty.h
sqlstmt.obj: config.h
sqlstmt.obj: connect.h
sqlstmt.obj: context.h
sqlstmt.obj: debug.h
sqlstmt.obj: describe.h
sqlstmt.obj: emalloc.h
sqlstmt.obj: esqlc.h
sqlstmt.obj: esqltype.h
sqlstmt.obj: internal.h
sqlstmt.obj: jlss.h
sqlstmt.obj: jlsstools.h
sqlstmt.obj: memory.h
sqlstmt.obj: output.h
sqlstmt.obj: sqlcmd.h
sqlstmt.obj: sqlconn.h
sqlstmt.obj: sqlerr.h
sqlstmt.obj: sqlstmt.ec
sqltoken.obj: debug.h
sqltoken.obj: sqltoken.c
sqltoken.obj: sqltoken.h
sqltype.obj: config.h
sqltype.obj: esqlc.h
sqltype.obj: esqltype.h
sqltype.obj: esqlutil.h
sqltype.obj: sqlquote.h
sqltype.obj: sqltype.ec
sqlunquote.obj: sqlquote.h
sqlunquote.obj: sqlunquote.c
sqlupload.obj: chktty.h
sqlupload.obj: config.h
sqlupload.obj: context.h
sqlupload.obj: debug.h
sqlupload.obj: emalloc.h
sqlupload.obj: esqlc.h
sqlupload.obj: esqltype.h
sqlupload.obj: getopt.h
sqlupload.obj: jlss.h
sqlupload.obj: jlsstools.h
sqlupload.obj: memory.h
sqlupload.obj: sqlcmd.h
sqlupload.obj: sqlerr.h
sqlupload.obj: sqlupload.c
sqlupload.obj: stderr.h
sqlupload.obj: upload.h
sqlver.obj: chktty.h
sqlver.obj: config.h
sqlver.obj: esqlc.h
sqlver.obj: esqltype.h
sqlver.obj: internal.h
sqlver.obj: jlss.h
sqlver.obj: jlsstools.h
sqlver.obj: memory.h
sqlver.obj: sqlver.c
sqlver.obj: stderr.h
stderr.obj: config.h
stderr.obj: stderr.c
stderr.obj: stderr.h
strcstrlit.obj: jlss.h
strcstrlit.obj: strcstrlit.c
strlower.obj: jlss.h
strlower.obj: strlower.c
strprefix.obj: jlss.h
strprefix.obj: strprefix.c
strupper.obj: jlss.h
strupper.obj: strupper.c
stuint4.obj: config.h
stuint4.obj: stldint.h
stuint4.obj: stuint4.c
timer.obj: config.h
timer.obj: timer.c
timer.obj: timer.h
tokencmp.obj: tokencmp.c
tokencmp.obj: tokencmp.h
updblob.obj: config.h
updblob.obj: connblob.h
updblob.obj: debug.h
updblob.obj: getopt.h
updblob.obj: stderr.h
updblob.obj: updblob.ec
upload.obj: chktty.h
upload.obj: config.h
upload.obj: connect.h
upload.obj: context.h
upload.obj: debug.h
upload.obj: describe.h
upload.obj: emalloc.h
upload.obj: esqlc.h
upload.obj: esqltype.h
upload.obj: esqlutil.h
upload.obj: jlss.h
upload.obj: jlsstools.h
upload.obj: kludge.h
upload.obj: memory.h
upload.obj: sqlcmd.h
upload.obj: sqlconn.h
upload.obj: sqlerr.h
upload.obj: sqlquote.h
upload.obj: stderr.h
upload.obj: upload.ec
upload.obj: upload.h
vstrcpy.obj: jlss.h
vstrcpy.obj: vstrcpy.c
